Repository defenseunicorns/leapfrogai, pull requests merged in 2024-08, with the labels that each got.

#852 fix(api): fix indexing files with api key auth
  packages/api/supabase/migrations/20240729193626_v0.10.0_api_keys_storage_objects.sql
  src/leapfrogai_api/backend/rag/index.py
  src/leapfrogai_api/backend/rag/leapfrogai_embeddings.py
  src/leapfrogai_api/data/crud_base.py
  src/leapfrogai_api/data/crud_vector_content.py
  src/leapfrogai_api/routers/openai/vector_stores.py
  tests/integration/api/conformance_test.py
Labels: possible-bug 🐛

#869 fix(ui): improve reliability of playwright test in workflow
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
  src/leapfrogai_ui/tests/api-keys.test.ts
  src/leapfrogai_ui/tests/file-management.test.ts
  src/leapfrogai_ui/tests/helpers/fileHelpers.ts
  src/leapfrogai_ui/tests/helpers/helpers.ts
Labels: bug

#873 feat(ui): settings/profile header btn re-design
  src/leapfrogai_ui/src/lib/components/LFHeader.svelte
  src/leapfrogai_ui/src/lib/components/LFHeader.test.ts
  src/leapfrogai_ui/tests/logout.test.ts
Labels: enhancement ✨

#881 bug(ui): chat box jump and sidebar squishing
  src/leapfrogai_ui/src/lib/components/ImportExport.svelte
  src/leapfrogai_ui/src/lib/components/LFSidebar.svelte
  src/leapfrogai_ui/src/lib/components/LFTextArea.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/tests/import_export.test.ts
  src/leapfrogai_ui/tests/sidebar.test.ts
Labels: bug

#882 chore(ui): improve sveltekit store mocking
  src/leapfrogai_ui/src/lib/components/modals/CreateApiKeyModal.test.ts
  src/leapfrogai_ui/src/lib/mocks/api-key-mocks.ts
  src/leapfrogai_ui/src/lib/mocks/svelte.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/api-keys.test.ts
  src/leapfrogai_ui/testUtils/fakeData/index.ts
  src/leapfrogai_ui/vitest-setup.ts
Labels: tech-debt 💳

#883 chore(ui): typescript updates and fix rag e2e tests
  src/leapfrogai_ui/src/lib/components/AssistantFileDropdown.svelte
  src/leapfrogai_ui/src/lib/mocks/api-key-mocks.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage.test.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage_no_thread.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/file-management.test.ts
  src/leapfrogai_ui/testUtils/fakeData/index.ts
  src/leapfrogai_ui/tests/rag.test.ts
  src/leapfrogai_ui/vitest-setup.ts
Labels: tech-debt 💳

#903 chore(ui): content security policy
  .github/workflows/ui-test.yaml
  src/leapfrogai_ui/.env.example
  src/leapfrogai_ui/playwright.config.ts
  src/leapfrogai_ui/src/lib/components/CopyToClipboardBtn.svelte
  src/leapfrogai_ui/svelte.config.js
Labels: tech-debt 💳

#898 feat(ui): 663- skeleton text for assistant responses
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/src/lib/components/MessagePendingSkeleton.svelte
  src/leapfrogai_ui/tests/chat.test.ts
Labels: enhancement ✨

#908 feat(ui): 669-annotations
  src/leapfrogai_ui/Dockerfile
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/src/app.css
  src/leapfrogai_ui/src/app.d.ts
  src/leapfrogai_ui/src/hooks.server.ts
  src/leapfrogai_ui/src/lib/components/Citatation.test.ts
  src/leapfrogai_ui/src/lib/components/Citation.svelte
  src/leapfrogai_ui/src/lib/components/FileProcessingPlaceholder.svelte
  src/leapfrogai_ui/src/lib/components/LFHeader.svelte
  src/leapfrogai_ui/src/lib/components/LFHeader.test.ts
  src/leapfrogai_ui/src/lib/components/Message.test.ts
  src/leapfrogai_ui/src/lib/constants/index.ts
  src/leapfrogai_ui/src/lib/constants/toastMessages.ts
  src/leapfrogai_ui/src/lib/mocks/file-mocks.ts
  src/leapfrogai_ui/src/lib/mocks/misc.ts
  src/leapfrogai_ui/src/lib/mocks/openai.ts
  src/leapfrogai_ui/src/lib/stores/ui.ts
  src/leapfrogai_ui/src/routes/+layout.server.ts
  src/leapfrogai_ui/src/routes/api/files/convert/+server.ts
  src/leapfrogai_ui/src/routes/api/files/convert/server.test.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage.test.ts
  src/leapfrogai_ui/src/routes/chat/+layout.server.ts
  src/leapfrogai_ui/src/routes/chat/+layout.svelte
  src/leapfrogai_ui/src/routes/chat/+layout.ts
  src/leapfrogai_ui/svelte.config.js
  src/leapfrogai_ui/tests/file-management.test.ts
  src/leapfrogai_ui/tests/global.teardown.ts
  src/leapfrogai_ui/tests/helpers/cleanup.ts
  src/leapfrogai_ui/tests/helpers/fileHelpers.ts
  src/leapfrogai_ui/tests/rag.test.ts
  src/leapfrogai_ui/vitest-setup.ts
  tests/data/test.csv
Labels: enhancement ✨

#900 feat(ui): 628-download-files
  src/leapfrogai_ui/src/lib/mocks/file-mocks.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/file-management.test.ts
  src/leapfrogai_ui/tests/file-management.test.ts
Labels: enhancement ✨

#913 fix(ui): CSP
  src/leapfrogai_api/pyproject.toml
  src/leapfrogai_ui/.env.example
  src/leapfrogai_ui/src/hooks.server.ts
  src/leapfrogai_ui/svelte.config.js
  src/leapfrogai_ui/tests/global.setup.ts
Labels: possible-bug 🐛

#919 bug(ui): fix spacing on non-chat pages
  src/leapfrogai_ui/src/app.css
  src/leapfrogai_ui/src/lib/components/LFSidebar.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+layout.svelte
Labels: bug

#929 chore(deps): pin all python deps and standardize pyprojects
  packages/llama-cpp-python/pyproject.toml
  packages/repeater/pyproject.toml
  packages/text-embeddings/pyproject.toml
  packages/vllm/pyproject.toml
  packages/whisper/pyproject.toml
  pyproject.toml
  src/leapfrogai_api/pyproject.toml
  src/leapfrogai_sdk/pyproject.toml
Labels: dependencies, tech-debt 💳

#931 chore: commitlint and labelint workflows
  .github/workflows/commit-lint.yaml
  .github/workflows/label-lint.yaml
  commitlint.config.js
Labels: chore

#855 chore(supabase): fix supabase-realtime
  packages/supabase/bitnami-values.yaml
  packages/supabase/chart/templates/supabase-realtime-secret.yaml
  packages/supabase/manifests/declarative-conf-configmap.yaml
  packages/supabase/migrations/20240808093300_v0.10.0_realtime_tenant.sql
  packages/supabase/zarf.yaml
Labels: chore

#923 fix(ui): playwright logout causes others to fail
  .github/workflows/e2e-playwright.yaml
  src/leapfrogai_ui/README.md
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/playwright.config.ts
  src/leapfrogai_ui/tests/fixtures.ts
  src/leapfrogai_ui/tests/global.setup.ts
  src/leapfrogai_ui/tests/helpers/apiHelpers.ts
  src/leapfrogai_ui/tests/helpers/cleanup.ts
  src/leapfrogai_ui/tests/logout.test.ts
Labels: bug

#922 feat(ui): refresh token early
  src/leapfrogai_ui/src/routes/+layout.svelte
Labels: enhancement

#943 chore: update README.md with clearer demo language
  README.md
  docs/imgs/walkthrough_thumbnail.jpg
Labels: chore

#909 chore(ui): use keycloak for e2es in workflow
  .github/actions/uds-cluster/action.yaml
  .github/config/uds-config.yaml
  .github/scripts/createUser.sh
  .github/workflows/e2e-playwright.yaml
  packages/k3d-gpu/Makefile
  src/leapfrogai_ui/.gitignore
  src/leapfrogai_ui/tests/global.setup.ts
Labels: tech-debt

#941 fix(ui): file upload data shows 1970
  .github/workflows/e2e-playwright.yaml
  src/leapfrogai_ui/src/lib/components/ImportExport.svelte
  src/leapfrogai_ui/src/lib/helpers/dates.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
  src/leapfrogai_ui/tests/fixtures.ts
  src/leapfrogai_ui/tests/global.setup.ts
  src/leapfrogai_ui/tests/helpers/apiHelpers.ts
  src/leapfrogai_ui/tests/helpers/cleanup.ts
  src/leapfrogai_ui/tests/helpers/fileHelpers.ts
Labels: bug

#962 docs: fixed command on Quick Start page (Building the UDS Bundle) docs
  website/content/en/docs/local-deploy-guide/quick_start.md
Labels: bug

#959 fix(vllm): initializes dictionary entry prior to usage
  packages/vllm/src/main.py
Labels: bug

#953 test(e2e): move openai client to fixture
  tests/e2e/conftest.py
  tests/e2e/test_llama.py
  tests/e2e/test_text_embeddings.py
  tests/e2e/test_whisper.py
  tests/e2e/utils.py
Labels: bug, tech-debt

#970 docs: update development.md
  docs/DEVELOPMENT.md
Labels: documentation

#966 fix(ui): csp prevents iframe content from showing
  src/leapfrogai_ui/src/hooks.server.ts
Labels: bug
