Repository defenseunicorns/leapfrogai, pull requests merged in 2024-10, with the labels that each got.

#1090 feat(api): reranking backend integrated in with rag
  .github/workflows/pytest.yaml
  packages/api/chart/values.yaml
  packages/api/values/registry1-values.yaml
  packages/api/values/upstream-values.yaml
  packages/api/zarf.yaml
  src/leapfrogai_api/README.md
  src/leapfrogai_api/backend/rag/query.py
  src/leapfrogai_api/main.py
  src/leapfrogai_api/pyproject.toml
  src/leapfrogai_api/routers/leapfrogai/rag.py
  src/leapfrogai_api/routers/leapfrogai/vector_stores.py
  src/leapfrogai_api/typedef/rag/__init__.py
  src/leapfrogai_api/typedef/rag/rag_types.py
  src/leapfrogai_api/typedef/vectorstores/search_types.py
  src/leapfrogai_api/utils/logging_tools.py
  src/leapfrogai_evals/pyproject.toml
  tests/integration/api/test_rag_files.py
  tests/pytest/leapfrogai_api/test_api.py
Labels: enhancement

#1149 chore: add Made for UDS badge verification task and workflow
  .github/scripts/uds_verification_report.py
  .github/workflows/e2e-llama-cpp-python.yaml
  .github/workflows/e2e-playwright.yaml
  .github/workflows/e2e-text-backend-full-cpu.yaml
  .github/workflows/e2e-text-embeddings.yaml
  .github/workflows/e2e-vllm.yaml
  .github/workflows/e2e-whisper.yaml
  .github/workflows/nightly-uds-badge-verification.yaml
  .github/workflows/uds-lint.yaml
  .gitignore
  .pre-commit-config.yaml
  docs/DEVELOPMENT.md
  packages/ui/chart/templates/ui/service.yaml
  tasks.yaml
Labels: chore

#1152 chore(docs): add workflow badges to readme
  README.md
Labels: documentation, community

#1166 feat(api): add prometheus monitoring
  packages/api/chart/templates/istio-admin.yaml
  packages/api/chart/templates/uds-package.yaml
  src/leapfrogai_api/main.py
  src/leapfrogai_api/pyproject.toml
Labels: enhancement

#1181 fix(whisper): failing gpu pod due to mangled env variable
  packages/whisper/Dockerfile
Labels: bug

#1177 fix: nightly snapshots repository typo
  .github/workflows/nightly-snapshot-release.yaml
Labels: bug

#854 feat(vllm)!: upgrade vllm backend and refactor deployment
  .github/actions/release/action.yaml
  .github/workflows/e2e-vllm.yaml
  Makefile
  bundles/dev/gpu/uds-config.yaml
  bundles/latest/gpu/uds-config.yaml
  docs/DEVELOPMENT.md
  packages/vllm/.env.example
  packages/vllm/Dockerfile
  packages/vllm/Makefile
  packages/vllm/README.md
  packages/vllm/chart/templates/deployment.yaml
  packages/vllm/chart/templates/leapfrogai-sdk-configmap.yaml
  packages/vllm/chart/templates/vllm-engine-configmap.yaml
  packages/vllm/chart/values.yaml
  packages/vllm/config.yaml
  packages/vllm/pyproject.toml
  packages/vllm/src/config.py
  packages/vllm/src/main.py
  packages/vllm/src/model_download.py
  packages/vllm/values/upstream-values.yaml
  packages/vllm/zarf-config.yaml
  packages/vllm/zarf.yaml
  src/leapfrogai_api/backend/grpc_client.py
  src/leapfrogai_api/backend/helpers.py
  src/leapfrogai_api/typedef/completion/completion_types.py
Labels: enhancement, dependencies, chore

#1158 chore(ui): better assistant error handling
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/src/lib/constants/errors.ts
  src/leapfrogai_ui/src/lib/constants/toastMessages.ts
  src/leapfrogai_ui/src/lib/helpers/chatHelpers.ts
  src/leapfrogai_ui/src/routes/api/chat/assistants/+server.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/tests/assistant-progress.test.ts
  src/leapfrogai_ui/tests/assistants.test.ts
Labels: chore

#842 docs: add ADR for RAG Evaluations Framework
  adr/0004-rag-eval-toolset.md
  adr/0007-rag-eval-framework.md
Labels: documentation, ADR 🧐

#1187 fix(docs): cron-job badges should look at main branch workflows only
  README.md
Labels: documentation

#1188 docs: update evals adr status
  adr/0004-rag-eval-toolset.md
  adr/0007-rag-eval-framework.md
Labels: documentation

#1168 chore(ui): style updates part1
  src/leapfrogai_ui/src/app.css
  src/leapfrogai_ui/src/lib/components/ChatFileUpload.svelte
  src/leapfrogai_ui/src/lib/components/FileChatActions.svelte
  src/leapfrogai_ui/src/lib/components/IconButton.svelte
  src/leapfrogai_ui/src/lib/components/ImportExport.svelte
  src/leapfrogai_ui/src/lib/components/LFFileUploadBtn.svelte
  src/leapfrogai_ui/src/lib/components/LFSidebar.svelte
  src/leapfrogai_ui/src/lib/components/LFSidebarDropdownItem.svelte
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/src/lib/components/PoweredByDU.svelte
  src/leapfrogai_ui/src/lib/components/SelectAssistantDropdown.svelte
  src/leapfrogai_ui/src/lib/stores/toast.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/ChatPageWithToast.test.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage.test.ts
  src/leapfrogai_ui/tests/chat.test.ts
  src/leapfrogai_ui/tests/helpers/threadHelpers.ts
  src/leapfrogai_ui/tests/sidebar.test.ts
Labels: chore

#1200 chore(ui): bump @sveltejs/kit and fix e2es
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/tests/assistants.test.ts
  src/leapfrogai_ui/tests/rag.test.ts
Labels: chore

#1176 feat: use chunk data in NIAH and QA evals
  src/leapfrogai_evals/.env.example
  src/leapfrogai_evals/README.md
  src/leapfrogai_evals/evals/niah_eval.py
  src/leapfrogai_evals/evals/qa_eval.py
  src/leapfrogai_evals/metrics/__init__.py
  src/leapfrogai_evals/metrics/niah_metrics.py
  src/leapfrogai_evals/models/lfai.py
  src/leapfrogai_evals/runners/niah_runner.py
  src/leapfrogai_evals/runners/qa_runner.py
Labels: enhancement

#1201 fix(api): annotations replacement text contains file ids
  src/leapfrogai_api/backend/converters.py
Labels: bug

#1202 chore: disables renovate and cron-job workflows
  .github/renovate.json5
  .github/workflows/nightly-snapshot-release.yaml
  .github/workflows/nightly-uds-badge-verification.yaml
  .github/workflows/scorecard.yaml
  .github/workflows/weekly-registry1-flavor-test.yaml
Labels: chore
