Repository defenseunicorns/leapfrogai, pull requests merged in 2024-07, with the labels that each got.

#699 fix(api): bump max tokens to maximum for Synthia-7B to prevent chopping
  src/leapfrogai_api/backend/types.py
  src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
Labels: bug

#679 Fetch individual threads
  src/leapfrogai_ui/README.md
  src/leapfrogai_ui/src/lib/components/ChatSidebar.svelte
  src/leapfrogai_ui/src/lib/components/ChatSidebar.test.ts
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/src/lib/components/Message.test.ts
  src/leapfrogai_ui/src/lib/components/MessageWithToast.test.svelte
  src/leapfrogai_ui/src/lib/components/ThreadOverflowMenu.svelte
  src/leapfrogai_ui/src/lib/helpers/chatHelpers.test.ts
  src/leapfrogai_ui/src/lib/helpers/chatHelpers.ts
  src/leapfrogai_ui/src/lib/helpers/threads.ts
  src/leapfrogai_ui/src/lib/mocks/chat-mocks.ts
  src/leapfrogai_ui/src/lib/mocks/svelte.ts
  src/leapfrogai_ui/src/lib/stores/threads.ts
  src/leapfrogai_ui/src/lib/stores/ui.ts
  src/leapfrogai_ui/src/lib/types/messages.d.ts
  src/leapfrogai_ui/src/routes/+page.svelte
  src/leapfrogai_ui/src/routes/api/threads/[thread_id]/+server.ts
  src/leapfrogai_ui/src/routes/api/threads/[thread_id]/server.test.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage.test.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage_no_thread.test.ts
  src/leapfrogai_ui/testUtils/fakeData/index.ts
  src/leapfrogai_ui/vitest-setup.ts
Labels: bug, tech-debt 💳

#713 chore(ui) - fix playwright e2e tests
  src/leapfrogai_ui/.env.example
  src/leapfrogai_ui/README.md
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/playwright.config.ts
  src/leapfrogai_ui/src/lib/components/AssistantForm.svelte
  src/leapfrogai_ui/src/lib/components/AttachFile.svelte
  src/leapfrogai_ui/src/lib/helpers/chatHelpers.ts
  src/leapfrogai_ui/src/lib/helpers/fileHelpers.ts
  src/leapfrogai_ui/src/lib/mocks/supabase-mocks.ts
  src/leapfrogai_ui/src/lib/stores/filesStore.ts
  src/leapfrogai_ui/src/lib/stores/threads.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/edit/[assistantId]/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/new/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
  src/leapfrogai_ui/testUtils/fakeData/index.ts
  src/leapfrogai_ui/tests/assistant-avatars.test.ts
  src/leapfrogai_ui/tests/assistants.test.ts
  src/leapfrogai_ui/tests/chat.test.ts
  src/leapfrogai_ui/tests/edit_message.test.ts
  src/leapfrogai_ui/tests/file-management.test.ts
  src/leapfrogai_ui/tests/fixtures.ts
  src/leapfrogai_ui/tests/fixtures/rehospitalisation-test.txt
  src/leapfrogai_ui/tests/global.setup.ts
  src/leapfrogai_ui/tests/global.teardown.ts
  src/leapfrogai_ui/tests/header.test.ts
  src/leapfrogai_ui/tests/helpers.ts
  src/leapfrogai_ui/tests/helpers/assistantHelpers.ts
  src/leapfrogai_ui/tests/helpers/fileHelpers.ts
  src/leapfrogai_ui/tests/helpers/helpers.ts
  src/leapfrogai_ui/tests/helpers/threadHelpers.ts
  src/leapfrogai_ui/tests/import_export.test.ts
  src/leapfrogai_ui/tests/rag.test.ts
  src/leapfrogai_ui/tests/sidebar.test.ts
Labels: bug, tech-debt 💳

#745 556 code blocks
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/src/lib/components/CopyToClipboardBtn.svelte
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/src/lib/components/modals/CopyApiKeyModal.svelte
  src/leapfrogai_ui/src/lib/types/markdown-it.d.ts
  src/leapfrogai_ui/src/lib/web-components/CodeBlock.js
  src/leapfrogai_ui/src/lib/web-components/styles.js
  src/leapfrogai_ui/src/routes/+layout.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/+page.svelte
  src/leapfrogai_ui/src/routes/chat/+layout.ts
  src/leapfrogai_ui/svelte.config.js
  src/leapfrogai_ui/tests/chat.test.ts
Labels: enhancement ✨

#658 feat(api): long lived api keys
  packages/api/supabase/migrations/20240618163044_v0.9.0_api_keys.sql
  src/leapfrogai_api/backend/rag/index.py
  src/leapfrogai_api/backend/rag/query.py
  src/leapfrogai_api/backend/security/__init__.py
  src/leapfrogai_api/backend/security/api_key.py
  src/leapfrogai_api/data/crud_api_key.py
  src/leapfrogai_api/data/crud_assistant.py
  src/leapfrogai_api/data/crud_base.py
  src/leapfrogai_api/data/crud_file_bucket.py
  src/leapfrogai_api/data/crud_file_object.py
  src/leapfrogai_api/data/crud_message.py
  src/leapfrogai_api/data/crud_run.py
  src/leapfrogai_api/data/crud_thread.py
  src/leapfrogai_api/data/crud_vector_store.py
  src/leapfrogai_api/data/crud_vector_store_file.py
  src/leapfrogai_api/main.py
  src/leapfrogai_api/pyproject.toml
  src/leapfrogai_api/routers/leapfrogai/auth.py
  src/leapfrogai_api/routers/leapfrogai/rag.py
  src/leapfrogai_api/routers/openai/assistants.py
  src/leapfrogai_api/routers/openai/audio.py
  src/leapfrogai_api/routers/openai/chat.py
  src/leapfrogai_api/routers/openai/completions.py
  src/leapfrogai_api/routers/openai/embeddings.py
  src/leapfrogai_api/routers/openai/files.py
  src/leapfrogai_api/routers/openai/messages.py
  src/leapfrogai_api/routers/openai/models.py
  src/leapfrogai_api/routers/openai/requests/create_message_request.py
  src/leapfrogai_api/routers/openai/runs.py
  src/leapfrogai_api/routers/openai/runs_steps.py
  src/leapfrogai_api/routers/openai/threads.py
  src/leapfrogai_api/routers/supabase_session.py
  tests/e2e/test_api.py
  tests/integration/api/test_auth.py
  tests/integration/api/test_vector_stores.py
  tests/pytest/leapfrogai_api/test_api.py
Labels: enhancement ✨

#769 526 feat(ui): keycloak logout
  src/leapfrogai_ui/src/routes/auth/+page.server.ts
  src/leapfrogai_ui/tests/logout.test.ts
Labels: enhancement ✨

#772 520 bug(ui) - defense unicorns badge on small screens
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/+layout.svelte
  src/leapfrogai_ui/src/styles/main.scss
Labels: bug

#768 feat(api): set api variable to expose by default
  .github/workflows/e2e.yaml
  Makefile
  packages/api/chart/templates/uds-package.yaml
  packages/api/chart/values.yaml
  packages/api/lfai-values.yaml
  packages/api/zarf.yaml
  uds-bundles/dev/README.md
Labels: tech-debt 💳

#776 bug(ui): 771-assistant no response
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/src/lib/web-components/CodeBlock.js
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
Labels: bug

#760 667 upload file types
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/src/lib/components/AssistantFileSelect.svelte
  src/leapfrogai_ui/src/lib/components/AttachFile.svelte
  src/leapfrogai_ui/src/lib/constants/index.ts
  src/leapfrogai_ui/src/lib/schemas/files.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
  src/leapfrogai_ui/tests/file-management.test.ts
  src/leapfrogai_ui/tests/helpers/fileHelpers.ts
Labels: enhancement ✨

#778 fix(ui) move deps to dev deps
  .gitignore
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/tests/helpers/fileHelpers.ts
Labels: tech-debt 💳

#785 670 feat(ui): users can select an annotation to viewdownload the original file
  src/leapfrogai_ui/.env.example
  src/leapfrogai_ui/README.md
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/src/lib/components/AssistantForm.svelte
  src/leapfrogai_ui/src/lib/components/Citation.svelte
  src/leapfrogai_ui/src/lib/components/CopyToClipboardBtn.svelte
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/src/lib/components/Message.test.ts
  src/leapfrogai_ui/src/lib/components/MessageWithToast.test.svelte
  src/leapfrogai_ui/src/lib/helpers/chatHelpers.test.ts
  src/leapfrogai_ui/src/lib/helpers/chatHelpers.ts
  src/leapfrogai_ui/src/lib/helpers/threads.ts
  src/leapfrogai_ui/src/lib/mocks/openai.ts
  src/leapfrogai_ui/src/lib/server/constants.ts
  src/leapfrogai_ui/src/lib/stores/threads.ts
  src/leapfrogai_ui/src/lib/stores/toast.ts
  src/leapfrogai_ui/src/lib/types/messages.d.ts
  src/leapfrogai_ui/src/lib/types/toast.d.ts
  src/leapfrogai_ui/src/lib/web-components/CodeBlock.js
  src/leapfrogai_ui/src/routes/api/chat/+server.ts
  src/leapfrogai_ui/src/routes/api/chat/assistants/+server.ts
  src/leapfrogai_ui/src/routes/api/files/[file_id]/+server.ts
  src/leapfrogai_ui/src/routes/api/files/[file_id]/server.test.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/api-keys.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/file-management.test.ts
  src/leapfrogai_ui/testUtils/fakeData/index.ts
  src/leapfrogai_ui/tests/chat.test.ts
  src/leapfrogai_ui/tests/edit_message.test.ts
  src/leapfrogai_ui/tests/fixtures.ts
  src/leapfrogai_ui/tests/helpers/assistantHelpers.ts
  src/leapfrogai_ui/tests/rag.test.ts
Labels: bug, enhancement ✨

#795 Update setup-zarf version
  .github/workflows/release.yaml
Labels: tech-debt 💳

#814 fix: Make errors when supabase is unavailable
  tests/make-tests.mk
Labels: possible-bug 🐛

#797 feat(backend): add k3d gpu image builder
  .github/workflows/release.yaml
  Makefile
  packages/k3d-gpu/Dockerfile
  packages/k3d-gpu/Makefile
  packages/k3d-gpu/README.md
  packages/k3d-gpu/plugin/device-plugin-daemonset.yaml
  packages/k3d-gpu/test/cuda-vector-add.yaml
Labels: enhancement ✨

#793 791 chore(ui): typescript cleanup
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/src/app.d.ts
  src/leapfrogai_ui/src/hooks.server.ts
  src/leapfrogai_ui/src/lib/components/LFMultiSelect.svelte
  src/leapfrogai_ui/src/lib/mocks/misc.ts
  src/leapfrogai_ui/src/lib/mocks/supabase-mocks.ts
  src/leapfrogai_ui/src/routes/+layout.server.ts
  src/leapfrogai_ui/src/routes/+layout.svelte
  src/leapfrogai_ui/src/routes/+layout.ts
  src/leapfrogai_ui/src/routes/+page.server.ts
  src/leapfrogai_ui/src/routes/+page.svelte
  src/leapfrogai_ui/src/routes/api/api-keys/delete/+server.ts
  src/leapfrogai_ui/src/routes/api/api-keys/delete/server.test.ts
  src/leapfrogai_ui/src/routes/api/assistants/+server.ts
  src/leapfrogai_ui/src/routes/api/assistants/delete/+server.ts
  src/leapfrogai_ui/src/routes/api/assistants/delete/server.test.ts
  src/leapfrogai_ui/src/routes/api/assistants/server.test.ts
  src/leapfrogai_ui/src/routes/api/chat/+server.ts
  src/leapfrogai_ui/src/routes/api/chat/assistants/+server.ts
  src/leapfrogai_ui/src/routes/api/chat/server.test.ts
  src/leapfrogai_ui/src/routes/api/files/+server.ts
  src/leapfrogai_ui/src/routes/api/files/[file_id]/+server.ts
  src/leapfrogai_ui/src/routes/api/files/[file_id]/server.test.ts
  src/leapfrogai_ui/src/routes/api/files/delete-check/+server.ts
  src/leapfrogai_ui/src/routes/api/files/delete-check/server.test.ts
  src/leapfrogai_ui/src/routes/api/files/delete/+server.ts
  src/leapfrogai_ui/src/routes/api/files/delete/server.test.ts
  src/leapfrogai_ui/src/routes/api/files/server.test.ts
  src/leapfrogai_ui/src/routes/api/messages/+server.ts
  src/leapfrogai_ui/src/routes/api/messages/[thread_id]/+server.ts
  src/leapfrogai_ui/src/routes/api/messages/[thread_id]/server.test.ts
  src/leapfrogai_ui/src/routes/api/messages/delete/+server.ts
  src/leapfrogai_ui/src/routes/api/messages/delete/server.test.ts
  src/leapfrogai_ui/src/routes/api/messages/new/+server.ts
  src/leapfrogai_ui/src/routes/api/messages/new/server.test.ts
  src/leapfrogai_ui/src/routes/api/messages/server.test.ts
  src/leapfrogai_ui/src/routes/api/threads/[thread_id]/+server.ts
  src/leapfrogai_ui/src/routes/api/threads/[thread_id]/server.test.ts
  src/leapfrogai_ui/src/routes/api/threads/delete/+server.ts
  src/leapfrogai_ui/src/routes/api/threads/delete/server.test.ts
  src/leapfrogai_ui/src/routes/api/threads/new/+server.ts
  src/leapfrogai_ui/src/routes/api/threads/new/server.test.ts
  src/leapfrogai_ui/src/routes/api/threads/update/label/+server.ts
  src/leapfrogai_ui/src/routes/api/threads/update/label/server.test.ts
  src/leapfrogai_ui/src/routes/auth/+page.server.ts
  src/leapfrogai_ui/src/routes/auth/callback/+server.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/api-keys-form-action.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/api-keys.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/assistant_form.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/edit/[assistantId]/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/new/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/files-upload-form-action.test.ts
  src/leapfrogai_ui/src/routes/chat/+layout.server.ts
  src/leapfrogai_ui/src/routes/chat/+layout.ts
  src/leapfrogai_ui/tests/fixtures.ts
Labels: tech-debt 💳

#833 fix(ui): playwright login without keycloak
  .github/workflows/e2e-shim.yaml
  .github/workflows/e2e.yaml
  src/leapfrogai_ui/README.md
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/src/lib/schemas/auth.ts
  src/leapfrogai_ui/src/routes/+page.server.ts
  src/leapfrogai_ui/src/routes/+page.svelte
  src/leapfrogai_ui/src/routes/auth/+page.server.ts
  src/leapfrogai_ui/src/routes/auth/confirm/+server.ts
  src/leapfrogai_ui/src/routes/auth/error/+page.svelte
  src/leapfrogai_ui/supabase/config.toml
  src/leapfrogai_ui/tests/global.setup.ts
Labels: bug

#820 Flowbite chat
  src/leapfrogai_ui/src/app.css
  src/leapfrogai_ui/src/lib/components/Citation.svelte
  src/leapfrogai_ui/src/lib/components/HeaderButton.svelte
  src/leapfrogai_ui/src/lib/components/IconButton.svelte
  src/leapfrogai_ui/src/lib/components/LFHeader.svelte
  src/leapfrogai_ui/src/lib/components/LFSidebar.svelte
  src/leapfrogai_ui/src/lib/components/LFSidebarDropdownItem.svelte
  src/leapfrogai_ui/src/lib/components/LFTextArea.svelte
  src/leapfrogai_ui/src/lib/components/LFTextArea.test.ts
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/src/lib/components/Message.test.ts
  src/leapfrogai_ui/src/lib/components/MessageWithToast.test.svelte
  src/leapfrogai_ui/src/lib/components/PoweredByDU.svelte
  src/leapfrogai_ui/src/lib/components/SelectAssistantDropdown.svelte
  src/leapfrogai_ui/src/routes/+layout.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+layout.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage.test.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage_no_thread.test.ts
  src/leapfrogai_ui/src/styles/main.scss
  src/leapfrogai_ui/tests/chat.test.ts
  src/leapfrogai_ui/tests/edit_message.test.ts
  src/leapfrogai_ui/tests/helpers/threadHelpers.ts
  src/leapfrogai_ui/tests/rag.test.ts
Labels: enhancement ✨

#836 fix: k3d gpu deployment on headless and compute-only gpus
  packages/k3d-gpu/plugin/device-plugin-daemonset.yaml
Labels: bug

#849 fix(ui): logout
  packages/ui/chart/templates/ui/deployment.yaml
  src/leapfrogai_ui/.env.example
  src/leapfrogai_ui/tests/logout.test.ts
Labels: bug
