Repository defenseunicorns/leapfrogai, pull requests merged in 2024-09, with the labels that each got.

#971 chore: update CODEOWNERS
  CODEOWNERS
Labels: chore

#958 chore: pin python dependencies in root pyproject
  pyproject.toml
Labels: dependencies, tech-debt

#945 feat: add RAG Evals Runner and Needle in a Haystack Evaluation
  .gitignore
  src/leapfrogai_evals/README.md
  src/leapfrogai_evals/__init__.py
  src/leapfrogai_evals/main.py
  src/leapfrogai_evals/metrics/__init__.py
  src/leapfrogai_evals/metrics/niah_metrics.py
  src/leapfrogai_evals/pyproject.toml
  src/leapfrogai_evals/runners/__init__.py
  src/leapfrogai_evals/runners/niah_runner.py
Labels: enhancement, python

#974 fix: correct fsGroup configuration in various deployments
  packages/api/chart/templates/api/deployment.yaml
  packages/api/chart/templates/migration-job.yaml
  packages/llama-cpp-python/chart/templates/deployment.yaml
  packages/llama-cpp-python/chart/values.yaml
  packages/repeater/chart/values.yaml
  packages/supabase/migrationChart/templates/migration-job.yaml
  packages/text-embeddings/chart/templates/deployment.yaml
  packages/text-embeddings/chart/values.yaml
  packages/ui/chart/templates/ui/migration-job.yaml
  packages/vllm/chart/templates/deployment.yaml
  packages/vllm/chart/values.yaml
  packages/whisper/chart/templates/deployment.yaml
  packages/whisper/chart/values.yaml
Labels: bug

#920 feat(api)!: initial integration of registry1 api flavor
  .github/actions/lfai-core/action.yaml
  .github/actions/uds-cluster/action.yaml
  .github/workflows/e2e-llama-cpp-python.yaml
  .github/workflows/e2e-playwright.yaml
  .github/workflows/e2e-registry1-weekly.yaml
  .github/workflows/e2e-text-embeddings.yaml
  .github/workflows/e2e-vllm.yaml
  .github/workflows/e2e-whisper.yaml
  .github/workflows/release.yaml
  Makefile
  README.md
  docs/DEVELOPMENT.md
  packages/api/Dockerfile
  packages/api/README.md
  packages/api/chart/Chart.yaml
  packages/api/chart/templates/_helpers.tpl
  packages/api/chart/templates/api/deployment.yaml
  packages/api/chart/templates/api/permissions.yaml
  packages/api/chart/templates/api/service.yaml
  packages/api/chart/templates/migration-job.yaml
  packages/api/chart/templates/namespace.yaml
  packages/api/chart/templates/uds-package.yaml
  packages/api/chart/values.yaml
  packages/api/common/zarf.yaml
  packages/api/config.example.yaml
  packages/api/lfai-values.yaml
  packages/api/values/registry1-values.yaml
  packages/api/values/upstream-values.yaml
  packages/api/zarf.yaml
  packages/llama-cpp-python/zarf.yaml
  packages/repeater/zarf.yaml
  packages/supabase/zarf.yaml
  packages/text-embeddings/zarf.yaml
  packages/ui/zarf.yaml
  packages/vllm/zarf.yaml
  packages/whisper/zarf.yaml
  website/content/en/docs/local-deploy-guide/components.md
  website/content/en/docs/local-deploy-guide/quick_start.md
Labels: dependencies, api

#942 chore(api): add background task for processing vectors
  .github/workflows/e2e-playwright.yaml
  .github/workflows/e2e-text-backend-full-cpu.yaml
  packages/text-embeddings/main.py
  pyproject.toml
  src/leapfrogai_api/backend/rag/index.py
  src/leapfrogai_api/routers/openai/vector_stores.py
  tests/e2e/test_text_backend_full.py
  tests/e2e/utils.py
Labels: blocked :stop_sign:, chore

#951 feat(ui): chat completion with files
  packages/ui/zarf.yaml
  src/leapfrogai_ui/.env.example
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/src/lib/components/ChatFileUploadForm.svelte
  src/leapfrogai_ui/src/lib/components/Citation.svelte
  src/leapfrogai_ui/src/lib/components/Citation.test.ts
  src/leapfrogai_ui/src/lib/components/ImportExport.svelte
  src/leapfrogai_ui/src/lib/components/LFFileUploadBtn.svelte
  src/leapfrogai_ui/src/lib/components/LFTextArea.svelte
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/src/lib/components/MessagePendingSkeleton.svelte
  src/leapfrogai_ui/src/lib/components/SidebarWrapper.svelte
  src/leapfrogai_ui/src/lib/components/UploadedFileCard.svelte
  src/leapfrogai_ui/src/lib/components/UploadedFileCards.svelte
  src/leapfrogai_ui/src/lib/constants/errors.ts
  src/leapfrogai_ui/src/lib/constants/index.ts
  src/leapfrogai_ui/src/lib/constants/toastMessages.ts
  src/leapfrogai_ui/src/lib/helpers/chatHelpers.test.ts
  src/leapfrogai_ui/src/lib/helpers/chatHelpers.ts
  src/leapfrogai_ui/src/lib/helpers/stringHelpers.test.ts
  src/leapfrogai_ui/src/lib/helpers/stringHelpers.ts
  src/leapfrogai_ui/src/lib/mocks/file-mocks.ts
  src/leapfrogai_ui/src/lib/schemas/chat.ts
  src/leapfrogai_ui/src/lib/schemas/files.ts
  src/leapfrogai_ui/src/lib/types/files.d.ts
  src/leapfrogai_ui/src/lib/types/messages.d.ts
  src/leapfrogai_ui/src/lib/utils/files.ts
  src/leapfrogai_ui/src/routes/api/files/convert/+server.ts
  src/leapfrogai_ui/src/routes/api/files/convert/[id]/+server.ts
  src/leapfrogai_ui/src/routes/api/files/convert/[id]/server.test.ts
  src/leapfrogai_ui/src/routes/api/files/convert/[id]/utils.ts
  src/leapfrogai_ui/src/routes/api/files/convert/server.test.ts
  src/leapfrogai_ui/src/routes/api/messages/new/+server.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage.test.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/form-action.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/api-keys-form-action.test.ts
  src/leapfrogai_ui/tests/assistants.test.ts
  src/leapfrogai_ui/tests/chat.test.ts
  src/leapfrogai_ui/tests/edit_message.test.ts
  src/leapfrogai_ui/tests/file-chat.test.ts
  src/leapfrogai_ui/tests/file-management.test.ts
  src/leapfrogai_ui/tests/fixtures.ts
  src/leapfrogai_ui/tests/global.setup.ts
  src/leapfrogai_ui/tests/helpers/fileHelpers.ts
  src/leapfrogai_ui/tests/helpers/helpers.ts
  src/leapfrogai_ui/tests/helpers/threadHelpers.ts
  src/leapfrogai_ui/tests/rag.test.ts
Labels: enhancement

#933 chore!: standardize flavors, bundle dir and ghcr namespace
  .github/workflows/e2e-registry1-weekly.yaml
  .github/workflows/release.yaml
  README.md
  bundles/dev/cpu/uds-bundle.yaml
  bundles/dev/cpu/uds-config.yaml
  bundles/dev/gpu/uds-bundle.yaml
  bundles/dev/gpu/uds-config.yaml
  bundles/latest/cpu/uds-bundle.yaml
  bundles/latest/cpu/uds-config.yaml
  bundles/latest/gpu/uds-bundle.yaml
  bundles/latest/gpu/uds-config.yaml
  docs/DEVELOPMENT.md
  website/content/en/docs/local-deploy-guide/quick_start.md
Labels: dependencies, tech-debt

#830 feat(api): adds migration for tracking vector store indexing status
  .github/actions/lfai-core/action.yaml
  packages/api/supabase/migrations/20240827103100_v0.11.1_indexing_status.sql
  pyproject.toml
  tests/e2e/test_supabase.py
  tests/e2e/utils.py
Labels: enhancement

#988 chore: update release workflow trigger type
  .github/workflows/release.yaml
  .github/workflows/tag-for-release.yaml
Labels: chore

#996 chore: rename indexing_status migration version
  packages/api/supabase/migrations/20240827103100_v0.12.0_indexing_status.sql
Labels: chore

#995 fix: run on thread containing an assistant without files
  src/leapfrogai_api/routers/openai/requests/run_create_params_request_base.py
Labels: bug, api

#985 chore(supabase): enable realtime for the file_objects table
  packages/api/supabase/migrations/20240905094300_v0.12.0_file_status.sql
  tests/e2e/test_supabase.py
Labels: chore

#967 feat(ui): persist file upload status
  src/leapfrogai_ui/src/app.css
  src/leapfrogai_ui/src/hooks.server.ts
  src/leapfrogai_ui/src/lib/components/AssistantFileDropdown.svelte
  src/leapfrogai_ui/src/lib/components/AssistantForm.svelte
  src/leapfrogai_ui/src/lib/components/AssistantProgressToast.svelte
  src/leapfrogai_ui/src/lib/components/AssistantProgressToast.test.ts
  src/leapfrogai_ui/src/lib/components/AssistantProgressToastContent.svelte
  src/leapfrogai_ui/src/lib/components/FileUploaderItem.svelte
  src/leapfrogai_ui/src/lib/components/LFHeader.svelte
  src/leapfrogai_ui/src/lib/components/LFSidebarDropdownItem.svelte
  src/leapfrogai_ui/src/lib/components/LFToast.svelte
  src/leapfrogai_ui/src/lib/components/SelectAssistantDropdown.svelte
  src/leapfrogai_ui/src/lib/components/ToastOverride.svelte
  src/leapfrogai_ui/src/lib/components/Toasts.svelte
  src/leapfrogai_ui/src/lib/components/modals/ConfirmFilesDeleteModal.svelte
  src/leapfrogai_ui/src/lib/constants/toastMessages.ts
  src/leapfrogai_ui/src/lib/helpers/toastHelpers.ts
  src/leapfrogai_ui/src/lib/stores/filesStore.ts
  src/leapfrogai_ui/src/lib/stores/toast.ts
  src/leapfrogai_ui/src/lib/stores/vectorStatusStore.ts
  src/leapfrogai_ui/src/lib/types/files.d.ts
  src/leapfrogai_ui/src/lib/types/toast.d.ts
  src/leapfrogai_ui/src/routes/+layout.svelte
  src/leapfrogai_ui/src/routes/api/vector-stores/files/+server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/assistant_form.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/edit/[assistantId]/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/new/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/file-management.test.ts
  src/leapfrogai_ui/tests/api-keys.test.ts
  src/leapfrogai_ui/tests/assistant-progress.test.ts
  src/leapfrogai_ui/tests/assistants.test.ts
  src/leapfrogai_ui/tests/chat.test.ts
  src/leapfrogai_ui/tests/edit_message.test.ts
  src/leapfrogai_ui/tests/file-management.test.ts
  src/leapfrogai_ui/tests/helpers/fileHelpers.ts
  src/leapfrogai_ui/tests/helpers/helpers.ts
  src/leapfrogai_ui/tests/helpers/navigationHelpers.ts
  src/leapfrogai_ui/tests/import_export.test.ts
  src/leapfrogai_ui/tests/rag.test.ts
  src/leapfrogai_ui/tests/sidebar.test.ts
Labels: enhancement

#997 chore(ui): add test for assistant with no files
  src/leapfrogai_ui/tests/chat.test.ts
Labels: chore

#998 docs(ui): remove bundle deploy steps
  website/content/en/docs/local-deploy-guide/quick_start.md
Labels: documentation

#999 fix: hotfix fix typo in release pipeline
  .github/workflows/release.yaml
Labels: bug, chore

#1003 fix: hotfix fix typo in release pipeline (again)
  .github/workflows/release.yaml
Labels: chore

#1004 chore(test): fix and re-activate integration and unit tests
  .github/workflows/pytest-shim.yaml
  .github/workflows/pytest.yaml
  .gitignore
  Makefile
  packages/repeater/Dockerfile
  packages/repeater/config.yaml
  packages/repeater/main.py
  packages/repeater/repeater.py
  src/leapfrogai_api/pyproject.toml
  tests/Makefile
  tests/README.md
  tests/integration/api/test_rag_files.py
  tests/pytest/leapfrogai_api/test_api.py
  tests/utils/client.py
Labels: tech-debt, chore

#1015 chore(test): prevent E2E tests from running in draft PRs
  .github/workflows/e2e-registry1-weekly.yaml
  .github/workflows/pytest.yaml
Labels: blocked :stop_sign:, chore

#992 docs(ui): add note about libreoffice to readme
  src/leapfrogai_ui/README.md
Labels: chore

#1028 fix: exclude registry1 weekly from release-please
  .github/release-please-config.json
Labels: bug

#1031 fix(sdk): best_of in completions was an int and should be a string
  pyproject.toml
  src/leapfrogai_sdk/audio/audio_pb2.py
  src/leapfrogai_sdk/audio/audio_pb2.pyi
  src/leapfrogai_sdk/audio/audio_pb2_grpc.py
  src/leapfrogai_sdk/chat/chat_pb2.py
  src/leapfrogai_sdk/chat/chat_pb2.pyi
  src/leapfrogai_sdk/chat/chat_pb2_grpc.py
  src/leapfrogai_sdk/completion/completion_pb2.py
  src/leapfrogai_sdk/completion/completion_pb2.pyi
  src/leapfrogai_sdk/completion/completion_pb2_grpc.py
  src/leapfrogai_sdk/embeddings/embeddings_pb2.py
  src/leapfrogai_sdk/embeddings/embeddings_pb2_grpc.py
  src/leapfrogai_sdk/name/name_pb2.py
  src/leapfrogai_sdk/name/name_pb2_grpc.py
  src/leapfrogai_sdk/proto/leapfrogai_sdk/completion/completion.proto
Labels: bug, api

#1027 chore(ui): package updates
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/src/app.css
  src/leapfrogai_ui/src/lib/components/AssistantProgressToast.svelte
  src/leapfrogai_ui/src/lib/components/LFToast.svelte
  src/leapfrogai_ui/src/lib/components/ToastOverride.svelte
Labels: chore

#1029 chore: split up make clean target
  Makefile
  mk-clean.mk
Labels: chore

#960 feat: add LLM as judge evaluations
  README.md
  src/leapfrogai_evals/.env.example
  src/leapfrogai_evals/README.md
  src/leapfrogai_evals/judges/__init__.py
  src/leapfrogai_evals/judges/claude_sonnet.py
  src/leapfrogai_evals/main.py
  src/leapfrogai_evals/metrics/annotation_relevancy.py
  src/leapfrogai_evals/metrics/correctness.py
  src/leapfrogai_evals/pyproject.toml
  src/leapfrogai_evals/runners/niah_runner.py
  src/leapfrogai_evals/runners/qa_runner.py
  src/leapfrogai_evals/utils/__init__.py
  src/leapfrogai_evals/utils/defaults.py
Labels: enhancement, python

#1025 fix(ui): small screen chat page style
  src/leapfrogai_ui/src/app.css
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+layout.svelte
Labels: bug

#1048 chore(api): update langchain to 0.2.12
  src/leapfrogai_api/pyproject.toml
Labels: dependencies, chore

#1024 fix(ui): header flicker and hamburger on thread page
  src/leapfrogai_ui/src/lib/components/LFHeader.svelte
  src/leapfrogai_ui/tests/header.test.ts
Labels: bug

#1042 chore(deps): ensure a dependency workflow checks all upstream resources and dependencies
  .github/dependabot.yml
  .github/renovate.json5
Labels: chore

#1057 chore: updates the versions to match the git commit sha
  .github/actions/uds-cluster/action.yaml
  .github/workflows/e2e-vllm.yaml
  .github/workflows/label-lint.yaml
Labels: chore

#1065 chore: variablize uds distro for uds make target
  packages/k3d-gpu/Makefile
Labels: chore

#978 fix(ui): delete avatar
  src/leapfrogai_ui/supabase/migrations/20240903204301_v0.13.0_avatars.sql
  src/leapfrogai_ui/tests/assistant-avatars.test.ts
Labels: bug

#1085 fix(api, tests): configmap reloading core dump
  src/leapfrogai_api/main.py
  src/leapfrogai_api/pyproject.toml
  src/leapfrogai_api/utils/config.py
  tests/pytest/leapfrogai_api/test_api.py
Labels: bug

#1073 fix(make): make clean changed to make clean-artifacts
  Makefile
  tests/Makefile
Labels: bug

#1046 feat(ui): translation
  src/leapfrogai_ui/src/lib/components/ChatFileUpload.svelte
  src/leapfrogai_ui/src/lib/components/ChatFileUploadForm.svelte
  src/leapfrogai_ui/src/lib/components/FileChatActions.svelte
  src/leapfrogai_ui/src/lib/components/FileChatActions.test.ts
  src/leapfrogai_ui/src/lib/components/LFSidebarDropdownItem.svelte
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/src/lib/components/UploadedFileCard.svelte
  src/leapfrogai_ui/src/lib/components/UploadedFileCards.svelte
  src/leapfrogai_ui/src/lib/constants/index.ts
  src/leapfrogai_ui/src/lib/constants/toastMessages.ts
  src/leapfrogai_ui/src/lib/helpers/apiHelpers.ts
  src/leapfrogai_ui/src/lib/helpers/fileHelpers.test.ts
  src/leapfrogai_ui/src/lib/helpers/fileHelpers.ts
  src/leapfrogai_ui/src/lib/mocks/chat-mocks.ts
  src/leapfrogai_ui/src/lib/mocks/openai.ts
  src/leapfrogai_ui/src/lib/schemas/chat.ts
  src/leapfrogai_ui/src/lib/schemas/files.ts
  src/leapfrogai_ui/src/lib/stores/threads.ts
  src/leapfrogai_ui/src/lib/types/files.d.ts
  src/leapfrogai_ui/src/lib/types/messages.d.ts
  src/leapfrogai_ui/src/lib/types/toast.d.ts
  src/leapfrogai_ui/src/routes/api/audio/translation/+server.ts
  src/leapfrogai_ui/src/routes/api/audio/translation/server.test.ts
  src/leapfrogai_ui/src/routes/api/files/convert/server.test.ts
  src/leapfrogai_ui/src/routes/api/files/parse-text/+server.ts
  src/leapfrogai_ui/src/routes/api/files/parse-text/server.test.ts
  src/leapfrogai_ui/src/routes/api/messages/new/+server.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/form-action.test.ts
  src/leapfrogai_ui/svelte.config.js
  src/leapfrogai_ui/testUtils/fakeData/index.ts
  src/leapfrogai_ui/tests/fixtures/spanish.m4a
  src/leapfrogai_ui/tests/translation.test.ts
Labels: enhancement

#1062 feat(ui): transcription
  src/leapfrogai_ui/src/lib/components/AssistantCard.svelte
  src/leapfrogai_ui/src/lib/components/AssistantFileSelect.svelte
  src/leapfrogai_ui/src/lib/components/FileChatActions.svelte
  src/leapfrogai_ui/src/lib/components/FileChatActions.test.ts
  src/leapfrogai_ui/src/lib/components/UploadedFileCard.svelte
  src/leapfrogai_ui/src/lib/constants/index.ts
  src/leapfrogai_ui/src/lib/constants/toastMessages.ts
  src/leapfrogai_ui/src/lib/mocks/chat-mocks.ts
  src/leapfrogai_ui/src/lib/mocks/openai.ts
  src/leapfrogai_ui/src/routes/api/audio/transcription/+server.ts
  src/leapfrogai_ui/src/routes/api/audio/transcription/server.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
  src/leapfrogai_ui/tests/fileChatActions.test.ts
Labels: enhancement

#1038 chore(sdk, api): fix types, enhance chat, audio and completion tests
  .github/workflows/e2e-llama-cpp-python.yaml
  .github/workflows/e2e-vllm.yaml
  .github/workflows/pytest.yaml
  .gitignore
  docs/DEVELOPMENT.md
  mk-clean.mk
  packages/repeater/main.py
  src/leapfrogai_api/backend/grpc_client.py
  src/leapfrogai_api/backend/helpers.py
  src/leapfrogai_api/typedef/completion/__init__.py
  src/leapfrogai_api/typedef/completion/completion_types.py
  src/leapfrogai_sdk/__init__.py
  src/leapfrogai_sdk/chat/chat_pb2.py
  src/leapfrogai_sdk/chat/chat_pb2.pyi
  src/leapfrogai_sdk/chat/chat_pb2_grpc.py
  src/leapfrogai_sdk/completion/completion_pb2.py
  src/leapfrogai_sdk/completion/completion_pb2.pyi
  src/leapfrogai_sdk/completion/completion_pb2_grpc.py
  src/leapfrogai_sdk/llm.py
  src/leapfrogai_sdk/proto/leapfrogai_sdk/chat/chat.proto
  src/leapfrogai_sdk/proto/leapfrogai_sdk/completion/completion.proto
  tests/Makefile
  tests/README.md
  tests/e2e/test_llama.py
  tests/e2e/test_llm_generation.py
  tests/pytest/leapfrogai_api/test_api.py
Labels: tech-debt, chore

#1087 feat(ui): summarization
  src/leapfrogai_ui/src/lib/components/FileChatActions.svelte
  src/leapfrogai_ui/src/lib/components/FileChatActions.test.ts
  src/leapfrogai_ui/src/lib/components/LFCarousel.svelte
  src/leapfrogai_ui/src/lib/components/LFCarousel.test.ts
  src/leapfrogai_ui/src/lib/components/LFCarouselWithSlot.test.svelte
  src/leapfrogai_ui/src/lib/components/LFControlButton.svelte
  src/leapfrogai_ui/src/lib/components/UploadedFileCards.svelte
  src/leapfrogai_ui/src/lib/constants/toastMessages.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/tests/fileChatActions.test.ts
  src/leapfrogai_ui/tests/translation.test.ts
Labels: enhancement

#964 feat(api,vllm,llama-cpp-python): add token counting feature with gRPC support
  packages/repeater/main.py
  src/leapfrogai_api/backend/grpc_client.py
  src/leapfrogai_api/main.py
  src/leapfrogai_api/routers/leapfrogai/count.py
  src/leapfrogai_api/typedef/counting/__init__.py
  src/leapfrogai_api/typedef/counting/token_count_types.py
  src/leapfrogai_sdk/__init__.py
  src/leapfrogai_sdk/counting/__init__.py
  src/leapfrogai_sdk/counting/counting_pb2.py
  src/leapfrogai_sdk/counting/counting_pb2.pyi
  src/leapfrogai_sdk/counting/counting_pb2_grpc.py
  src/leapfrogai_sdk/llm.py
  src/leapfrogai_sdk/proto/leapfrogai_sdk/counting/counting.proto
  src/leapfrogai_sdk/serve.py
  tests/integration/api/test_token_count.py
  tests/pytest/leapfrogai_api/test_api.py
Labels: enhancement

#1086 fix(ui): temperature slider
  src/leapfrogai_ui/src/lib/components/AssistantForm.svelte
  src/leapfrogai_ui/tests/assistants.test.ts
  src/leapfrogai_ui/tests/helpers/assistantHelpers.ts
Labels: bug

#1094 chore(deps): update dependency ai to v3.4.0
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
Labels: chore

#1104 chore(ui): streaming text response deprecated
  src/leapfrogai_ui/package-lock.json
  src/leapfrogai_ui/package.json
  src/leapfrogai_ui/src/lib/mocks/chat-mocks.ts
  src/leapfrogai_ui/src/routes/api/chat/+server.ts
Labels: chore

#1078 feat: 1049 add standard evaluation benchmarks to lfai evals
  src/leapfrogai_evals/.env.example
  src/leapfrogai_evals/README.md
  src/leapfrogai_evals/evals/__init__.py
  src/leapfrogai_evals/evals/human_eval.py
  src/leapfrogai_evals/evals/mmlu.py
  src/leapfrogai_evals/evals/niah_eval.py
  src/leapfrogai_evals/evals/qa_eval.py
  src/leapfrogai_evals/judges/__init__.py
  src/leapfrogai_evals/main.py
  src/leapfrogai_evals/metrics/__init__.py
  src/leapfrogai_evals/models/__init__.py
  src/leapfrogai_evals/models/claude_sonnet.py
  src/leapfrogai_evals/models/lfai.py
  src/leapfrogai_evals/pyproject.toml
  src/leapfrogai_evals/runners/__init__.py
  src/leapfrogai_evals/runners/niah_runner.py
Labels: enhancement, python

#1116 chore(ui): improve e2e playwright test stability
  src/leapfrogai_ui/src/lib/components/Message.test.ts
  src/leapfrogai_ui/testUtils/fakeData/index.ts
  src/leapfrogai_ui/tests/assistant-avatars.test.ts
  src/leapfrogai_ui/tests/assistant-progress.test.ts
  src/leapfrogai_ui/tests/assistants.test.ts
  src/leapfrogai_ui/tests/chat.test.ts
  src/leapfrogai_ui/tests/fileChatActions.test.ts
  src/leapfrogai_ui/tests/global.teardown.ts
  src/leapfrogai_ui/tests/helpers/assistantHelpers.ts
  src/leapfrogai_ui/tests/helpers/cleanup.ts
  src/leapfrogai_ui/tests/helpers/fileHelpers.ts
  src/leapfrogai_ui/tests/helpers/navigationHelpers.ts
  src/leapfrogai_ui/tests/helpers/threadHelpers.ts
  src/leapfrogai_ui/tests/rag.test.ts
Labels: chore

#1066 fix(whisper): fix whisper transcription of non-english audio
  packages/whisper/Makefile
  packages/whisper/README.md
  packages/whisper/main.py
  tests/data/russian.mp3
  tests/e2e/test_whisper.py
Labels: bug

#1155 fix: indentation in text-embeddings and whisper deployments
  packages/text-embeddings/chart/templates/deployment.yaml
  packages/whisper/chart/templates/deployment.yaml
Labels: bug

#1159 fix(api): make model field optional in ModifyAssistantRequest type
  src/leapfrogai_api/typedef/assistants/assistant_types.py
  tests/conformance/test_conformance_assistants.py
  tests/utils/client.py
Labels: bug

#1141 chore(test, release): nightly snapshot release and upgrade testing
  .github/actions/release/action.yaml
  .github/actions/uds-cluster/action.yaml
  .github/release-please-config.json
  .github/workflows/nightly-snapshot-release.yaml
  .github/workflows/release.yaml
Labels: chore

#1165 chore(api, tests): refactor api tests to centralize file pathing
  tests/Makefile
  tests/README.md
  tests/conformance/test_assistants.py
  tests/conformance/test_completions.py
  tests/conformance/test_files.py
  tests/conformance/test_messages.py
  tests/conformance/test_runs.py
  tests/conformance/test_threads.py
  tests/conformance/test_tools.py
  tests/conformance/test_vectorstore.py
  tests/e2e/test_llm_generation.py
  tests/e2e/test_text_embeddings.py
  tests/e2e/test_whisper.py
  tests/integration/api/test_assistants.py
  tests/integration/api/test_files.py
  tests/integration/api/test_rag_files.py
  tests/integration/api/test_vector_stores.py
  tests/load/loadtest.py
  tests/pytest/leapfrogai_api/test_api.py
  tests/utils/client.py
  tests/utils/data_path.py
Labels: chore

#1164 feat(api): openai compliant annotations and vector_content retrieval
  src/leapfrogai_api/backend/composer.py
  src/leapfrogai_api/backend/converters.py
  src/leapfrogai_api/backend/rag/index.py
  src/leapfrogai_api/data/crud_vector_content.py
  src/leapfrogai_api/routers/leapfrogai/vector_stores.py
  src/leapfrogai_api/typedef/__init__.py
  src/leapfrogai_api/typedef/common.py
  src/leapfrogai_api/typedef/vectorstores/__init__.py
  src/leapfrogai_api/typedef/vectorstores/search_types.py
  tests/conformance/test_threads.py
  tests/conformance/test_tools.py
  tests/data/test_with_data.txt
  tests/integration/api/routes/leapfrogai/test_vector_stores.py
  tests/utils/client.py
Labels: enhancement

#1151 fix(ui): assistants chat
  src/leapfrogai_ui/src/app.d.ts
  src/leapfrogai_ui/src/lib/components/AssistantAvatar.svelte
  src/leapfrogai_ui/src/lib/components/AssistantCard.svelte
  src/leapfrogai_ui/src/lib/components/AssistantFileSelect.svelte
  src/leapfrogai_ui/src/lib/components/AssistantFileSelect.test.ts
  src/leapfrogai_ui/src/lib/components/AssistantForm.svelte
  src/leapfrogai_ui/src/lib/components/AssistantProgressToast.test.ts
  src/leapfrogai_ui/src/lib/components/ChatFileUpload.svelte
  src/leapfrogai_ui/src/lib/components/FileChatActions.test.ts
  src/leapfrogai_ui/src/lib/components/LFHeader.test.ts
  src/leapfrogai_ui/src/lib/components/Message.svelte
  src/leapfrogai_ui/src/lib/components/Message.test.ts
  src/leapfrogai_ui/src/lib/components/SelectAssistantDropdown.svelte
  src/leapfrogai_ui/src/lib/components/Sidebar.test.ts
  src/leapfrogai_ui/src/lib/components/UploadedFileCard.svelte
  src/leapfrogai_ui/src/lib/components/modals/ConfirmFilesDeleteModal.svelte
  src/leapfrogai_ui/src/lib/components/modals/DeleteApiKeyModal.svelte
  src/leapfrogai_ui/src/lib/constants/index.ts
  src/leapfrogai_ui/src/lib/helpers/fileHelpers.ts
  src/leapfrogai_ui/src/lib/mocks/file-mocks.ts
  src/leapfrogai_ui/src/lib/stores/assistantsStore.ts
  src/leapfrogai_ui/src/lib/stores/filesStore.ts
  src/leapfrogai_ui/src/lib/stores/index.ts
  src/leapfrogai_ui/src/lib/stores/threads.ts
  src/leapfrogai_ui/src/lib/types/files.d.ts
  src/leapfrogai_ui/src/routes/api/api-keys/delete/+server.ts
  src/leapfrogai_ui/src/routes/api/files/delete/+server.ts
  src/leapfrogai_ui/src/routes/api/files/delete/check/+server.ts
  src/leapfrogai_ui/src/routes/api/files/delete/check/server.test.ts
  src/leapfrogai_ui/src/routes/api/helpers.ts
  src/leapfrogai_ui/src/routes/api/threads/+server.ts
  src/leapfrogai_ui/src/routes/api/threads/[thread_id]/+server.ts
  src/leapfrogai_ui/src/routes/api/threads/server.test.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage.test.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage_no_thread.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/api-keys/api-keys.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/assistant_form.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/assistants-management-page.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/edit/[assistantId]/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/new/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/file-management.test.ts
  src/leapfrogai_ui/src/routes/chat/+layout.server.ts
  src/leapfrogai_ui/src/routes/chat/+layout.ts
  src/leapfrogai_ui/tests/api-keys.test.ts
  src/leapfrogai_ui/tests/assistant-avatars.test.ts
  src/leapfrogai_ui/tests/assistants.test.ts
  src/leapfrogai_ui/tests/file-chat.test.ts
  src/leapfrogai_ui/tests/file-management.test.ts
Labels: bug

#1163 fix: remove nightly snapshots release workflow from release-please
  .github/release-please-config.json
  .github/workflows/nightly-snapshot-release.yaml
Labels: bug

#1170 fix(ui): allow large transcribe and translate responses
  src/leapfrogai_ui/src/lib/components/FileChatActions.svelte
Labels: bug
