Repository defenseunicorns/leapfrogai, pull requests merged in 2024-06, with the labels that each got.

#468 feat(api): vector store endpoints
  README.md
  packages/api/Dockerfile
  packages/api/chart/templates/api/deployment.yaml
  packages/api/chart/values.yaml
  packages/api/zarf.yaml
  src/leapfrogai_api/README.md
  src/leapfrogai_api/backend/rag/__init__.py
  src/leapfrogai_api/backend/rag/document_loader.py
  src/leapfrogai_api/backend/rag/index.py
  src/leapfrogai_api/backend/rag/leapfrogai_embeddings.py
  src/leapfrogai_api/backend/rag/query.py
  src/leapfrogai_api/backend/types.py
  src/leapfrogai_api/data/crud_assistant_object.py
  src/leapfrogai_api/data/crud_base.py
  src/leapfrogai_api/data/crud_file_object.py
  src/leapfrogai_api/data/crud_vector_store.py
  src/leapfrogai_api/data/crud_vector_store_file.py
  src/leapfrogai_api/main.py
  src/leapfrogai_api/pyproject.toml
  src/leapfrogai_api/routers/leapfrogai/__init__.py
  src/leapfrogai_api/routers/leapfrogai/rag.py
  src/leapfrogai_api/routers/openai/assistants.py
  src/leapfrogai_api/routers/openai/embeddings.py
  src/leapfrogai_api/routers/openai/files.py
  src/leapfrogai_api/routers/openai/vector_store.py
  src/leapfrogai_api/routers/openai/vector_stores.py
  src/leapfrogai_api/routers/supabase_session.py
  supabase/migrations/20240502193159_init-vector-stores.sql
  supabase/migrations/20240603183253_vector-store-rls.sql
  tests/data/test.csv
  tests/data/test.md
  tests/integration/api/test_files.py
  tests/integration/api/test_vector_stores.py
  tests/pytest/leapfrogai_api/test_api.py
Labels: enhancement ✨

#604 602 scroll bug v2
  src/leapfrogai_ui/src/lib/components/LFContent.svelte
  src/leapfrogai_ui/src/routes/+layout.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/+layout.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/+layout.svelte
Labels: bug

#609 fix: handle database permissions errors and workflow exceptions
  .github/workflows/e2e.yaml
  packages/api/chart/templates/migration-job.yaml
  packages/api/chart/values.yaml
  packages/api/zarf.yaml
  packages/ui/chart/templates/ui/migration-job.yaml
  packages/ui/chart/ui-values.yaml
  tests/e2e/test_api.py
  tests/e2e/test_llama.py
  tests/e2e/test_supabase.py
  tests/e2e/test_text_embeddings.py
  tests/e2e/test_whisper.py
  tests/e2e/utils.py
Labels: bug

#554 feat(api): Threads and Message Endpoints
  packages/api/supabase/migrations/20240522141100_threads_runs_messages_steps.sql
  src/leapfrogai_api/.gitignore
  src/leapfrogai_api/Makefile
  src/leapfrogai_api/README.md
  src/leapfrogai_api/backend/types.py
  src/leapfrogai_api/data/crud_assistant.py
  src/leapfrogai_api/data/crud_message.py
  src/leapfrogai_api/data/crud_thread.py
  src/leapfrogai_api/routers/openai/assistants.py
  src/leapfrogai_api/routers/openai/threads.py
  tests/integration/api/test_threads.py
  tests/integration/api/test_vector_stores.py
Labels: enhancement ✨

#617 539 UI enhancements v2
  src/leapfrogai_ui/src/lib/components/ChatSidebar.svelte
  src/leapfrogai_ui/src/lib/components/ChatSidebar.test.ts
  src/leapfrogai_ui/src/lib/components/ImportExport.svelte
  src/leapfrogai_ui/src/lib/components/ImportExport.test.ts
  src/leapfrogai_ui/src/lib/components/LFFileUploader.svelte
  src/leapfrogai_ui/src/lib/components/LFHeader.svelte
  src/leapfrogai_ui/src/lib/components/LFHeader.test.ts
  src/leapfrogai_ui/src/lib/stores/threads.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/+layout.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/assistants-management-page.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+layout.svelte
  src/leapfrogai_ui/src/routes/chat/+layout.server.ts
  src/leapfrogai_ui/src/routes/chat/+layout.ts
  src/leapfrogai_ui/tests/assistants.test.ts
  src/leapfrogai_ui/tests/file-management.test.ts
  src/leapfrogai_ui/tests/import_export.test.ts
Labels: bug, enhancement ✨

#608 532 upload file with assistant
  src/leapfrogai_ui/src/lib/components/AssistantFileSelect.svelte
  src/leapfrogai_ui/src/lib/components/AssistantFileSelect.test.ts
  src/leapfrogai_ui/src/lib/components/AssistantForm.svelte
  src/leapfrogai_ui/src/lib/components/FileUploadMenuItem.svelte
  src/leapfrogai_ui/src/lib/components/LFMultiSelect.svelte
  src/leapfrogai_ui/src/lib/stores/filesStore.ts
  src/leapfrogai_ui/src/lib/stores/index.ts
  src/leapfrogai_ui/src/lib/types/files.d.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/chatpage.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/edit/[assistantId]/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/new/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.server.ts
  src/leapfrogai_ui/tests/file-management.test.ts
  src/leapfrogai_ui/tests/helpers.ts
  src/leapfrogai_ui/tests/rag.test.ts
Labels: enhancement ✨

#629 573 api integration
  packages/ui/chart/templates/ui/deployment.yaml
  packages/ui/zarf.yaml
  src/leapfrogai_ui/.env.example
  src/leapfrogai_ui/README.md
  src/leapfrogai_ui/src/lib/helpers/chatHelpers.test.ts
  src/leapfrogai_ui/src/lib/helpers/chatHelpers.ts
  src/leapfrogai_ui/src/lib/server/constants.ts
  src/leapfrogai_ui/src/routes/api/assistants/+server.ts
  src/leapfrogai_ui/src/routes/api/assistants/delete/+server.ts
  src/leapfrogai_ui/src/routes/api/chat/+server.ts
  src/leapfrogai_ui/src/routes/api/chat/assistants/+server.ts
  src/leapfrogai_ui/src/routes/api/files/+server.ts
  src/leapfrogai_ui/src/routes/api/files/delete/+server.ts
  src/leapfrogai_ui/src/routes/api/messages/+server.ts
  src/leapfrogai_ui/src/routes/api/messages/[thread_id]/+server.ts
  src/leapfrogai_ui/src/routes/api/messages/delete/+server.ts
  src/leapfrogai_ui/src/routes/api/messages/new/+server.ts
  src/leapfrogai_ui/src/routes/api/threads/[thread_id]/+server.ts
  src/leapfrogai_ui/src/routes/api/threads/delete/+server.ts
  src/leapfrogai_ui/src/routes/api/threads/new/+server.ts
  src/leapfrogai_ui/src/routes/api/threads/update/label/+server.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/edit/[assistantId]/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/new/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.server.ts
  src/leapfrogai_ui/src/routes/chat/+layout.server.ts
  src/leapfrogai_ui/tests/helpers.ts
  src/leapfrogai_ui/vitest-setup.ts
Labels: tech-debt 💳

#635 fix(build): supabase bundle deployment order
  .github/workflows/e2e.yaml
  README.md
  tests/e2e/README.md
  uds-bundles/dev/cpu/uds-bundle.yaml
  uds-bundles/dev/gpu/uds-bundle.yaml
  uds-bundles/latest/cpu/uds-bundle.yaml
  uds-bundles/latest/gpu/uds-bundle.yaml
  website/content/en/docs/local deploy guide/quick_start.md
Labels: bug

#641 UI bug fixes
  src/leapfrogai_ui/src/lib/components/AssistantFileSelect.svelte
  src/leapfrogai_ui/src/lib/stores/filesStore.ts
  src/leapfrogai_ui/src/routes/chat/(dashboard)/[[thread_id]]/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
  src/leapfrogai_ui/tests/file-management.test.ts
  src/leapfrogai_ui/tests/fixtures/test.txt
Labels: bug

#653 fix(docs): readme table of contents and ordered list rendering
  README.md
Labels: documentation

#627 560 warning when deleting files
  src/leapfrogai_ui/src/lib/components/AssistantTile.svelte
  src/leapfrogai_ui/src/lib/components/ConfirmAssistantDeleteModal.svelte
  src/leapfrogai_ui/src/lib/mocks/file-mocks.ts
  src/leapfrogai_ui/src/lib/mocks/openai.ts
  src/leapfrogai_ui/src/lib/schemas/files.ts
  src/leapfrogai_ui/src/routes/api/files/delete-check/+server.ts
  src/leapfrogai_ui/src/routes/api/files/delete-check/server.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/assistants-management/assistant_form.test.ts
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/+page.svelte
  src/leapfrogai_ui/src/routes/chat/(settings)/file-management/file-management.test.ts
  src/leapfrogai_ui/testUtils/fakeData/index.ts
  src/leapfrogai_ui/tests/file-management.test.ts
  src/leapfrogai_ui/tests/helpers.ts
Labels: enhancement ✨
